### ISSUE TITLE
1.0.0-alpha-4 logger is undefined. 

### ISSUE THREAD

**Issue by thejones** [trailsjs/trailpack-core#19]
TypeError: Cannot read property 'logger' of undefined

Seems to be introduced in alpha-4

**Comment by jaumard** [comment]
+1 on this

**Comment by tjwebb** [comment]
@jaumard @thejones is this still an issue?

**Comment by jaumard** [comment]
@tjwebb can't remember when this occurred :/ and don't have it recently so for me no

**Comment by tjwebb** [comment]
Cool no problem, just cleaning out some old issues.
